# SPDX-FileCopyrightText: 2026 Kevin Stenzel
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""FRP tunnel CRUD (/api/frp/tunnels): the visitor-port conflict (409), automatic port assignment +
STCP secret autogeneration, and the duplicate-name conflict — none of which had a test, so a
regression removing the conflict check would only surface as frps misbehaviour in production (6.74)."""

from app.modules.frp.models import FrpServerConfig, FrpTunnel
from app.modules.servers.models import Server


def _login(client, username: str, password: str) -> dict:
    r = client.post("/api/auth/login", json={"username": username, "password": password})
    assert r.status_code == 200, r.text
    return {"Authorization": f"Bearer {r.json()['access_token']}"}


def _seed(db) -> None:
    db.add(
        FrpServerConfig(
            id="cfg-1",
            name="Default",
            server_addr="frps.example.net",
            bind_port=7000,
            auth_token="secret-frps-auth",
        )
    )
    db.add(Server(id="srv-a", name="serverA", hostname="a.example.test"))
    db.add(
        FrpTunnel(
            id="t-a",
            server_id="srv-a",
            frp_config_id="cfg-1",
            name="a-ssh",
            tunnel_type="stcp",
            protocol="ssh",
            local_port=22,
            secret_key="existing-secret",
            visitor_port=6000,
            enabled=True,
        )
    )
    db.commit()


def _body(**over) -> dict:
    body = {
        "server_id": "srv-a",
        "frp_config_id": "cfg-1",
        "name": "neu",
        "tunnel_type": "stcp",
        "protocol": "ssh",
        "local_port": 22,
    }
    body.update(over)
    return body


def test_visitor_port_conflict_is_409(test_client, db_session, admin_user):
    _seed(db_session)
    h = _login(test_client, "admin", "adminpass")
    r = test_client.post("/api/frp/tunnels", json=_body(visitor_port=6000), headers=h)
    assert r.status_code == 409, r.text  # 6000 is already bound by t-a


def test_duplicate_name_is_409(test_client, db_session, admin_user):
    _seed(db_session)
    h = _login(test_client, "admin", "adminpass")
    r = test_client.post("/api/frp/tunnels", json=_body(name="a-ssh", visitor_port=6002), headers=h)
    assert r.status_code == 409, r.text  # name a-ssh already exists


def test_stcp_create_autogenerates_secret_and_port(test_client, db_session, admin_user):
    _seed(db_session)
    h = _login(test_client, "admin", "adminpass")
    # No visitor_port, no secret_key -> both auto-assigned.
    r = test_client.post("/api/frp/tunnels", json=_body(name="auto"), headers=h)
    assert r.status_code == 201, r.text
    data = r.json()
    assert data["visitorPort"] != 6000  # auto-assigned, not the taken port
    assert data["secretKey"]  # STCP secret autogenerated
