#!/bin/sh
set -e
systemctl stop srm-frpc-sync.timer 2>/dev/null || true
systemctl stop frpc.service 2>/dev/null || true
systemctl disable srm-frpc-sync.timer 2>/dev/null || true
systemctl disable frpc.service 2>/dev/null || true
