// SPDX-FileCopyrightText: 2026 Kevin Stenzel
//
// SPDX-License-Identifier: GPL-3.0-or-later

// Package httpclient builds the TLS-aware HTTP client shared by the agent
// components (frpc sync, monitor push, provisioning).
package httpclient

import (
	"crypto/sha256"
	"crypto/tls"
	"crypto/x509"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"time"
)

// ErrPermanent marks an HTTP failure that a retry cannot fix — the agent's
// credentials or identity are the problem (rotated/revoked API key, deleted
// server), not a transient outage. A oneshot run (systemd timer) surfaces it as a
// non-zero exit so OnFailure fires, instead of silently staying green while
// misconfigured (4.80/4.81).
var ErrPermanent = errors.New("permanenter Fehler")

// isPermanentStatus classifies the 4xx codes an agent retry cannot resolve: 401
// (rotated/revoked key), 403 (key lacks the server binding), 404 (server
// deprovisioned). Everything else (5xx, 429, network/timeout) is transient.
func isPermanentStatus(code int) bool {
	return code == http.StatusUnauthorized ||
		code == http.StatusForbidden ||
		code == http.StatusNotFound
}

// noRedirect makes a client return a 3xx as its final response instead of
// following it. Go only strips Authorization/Cookie on a cross-host redirect, so the
// agent's custom auth headers (X-API-Key, X-Provision-Token) would otherwise leak to
// a redirect target chosen by a compromised server. No legitimate agent endpoint
// (activate, config, config-hash, report, enroll, renew) redirects (3.43).
func noRedirect(req *http.Request, via []*http.Request) error {
	return http.ErrUseLastResponse
}

// New creates an HTTP client with optional TLS settings: a pinned CA
// certificate (cacert, PEM file path) or disabled verification (insecure).
func New(cacert string, insecure bool, timeout time.Duration) (*http.Client, error) {
	tlsCfg := &tls.Config{MinVersion: tls.VersionTLS12}
	if insecure {
		tlsCfg.InsecureSkipVerify = true
	} else if cacert != "" {
		pem, err := os.ReadFile(cacert)
		if err != nil {
			return nil, fmt.Errorf("CA-Zertifikat lesen: %w", err)
		}
		pool := x509.NewCertPool()
		if !pool.AppendCertsFromPEM(pem) {
			return nil, fmt.Errorf("CA-Zertifikat ungueltig")
		}
		tlsCfg.RootCAs = pool
	}
	return &http.Client{
		Timeout:       timeout,
		Transport:     &http.Transport{TLSClientConfig: tlsCfg},
		CheckRedirect: noRedirect,
	}, nil
}

// NewMTLS builds a client that presents the given client certificate (cert +
// key PEM files) and trusts ONLY the given CA bundle — system roots are NOT
// added (ADR 0001 D2: validate every leaf against our pinned CA, so even a
// compromised public CA is rejected). Used for all server pushes once the agent
// is enrolled.
func NewMTLS(certPath, keyPath, caPath string, timeout time.Duration) (*http.Client, error) {
	cert, err := tls.LoadX509KeyPair(certPath, keyPath)
	if err != nil {
		return nil, fmt.Errorf("Client-Zertifikat laden: %w", err)
	}
	caPEM, err := os.ReadFile(caPath)
	if err != nil {
		return nil, fmt.Errorf("CA-Zertifikat lesen: %w", err)
	}
	pool := x509.NewCertPool()
	if !pool.AppendCertsFromPEM(caPEM) {
		return nil, fmt.Errorf("CA-Zertifikat ungueltig")
	}
	tlsCfg := &tls.Config{
		Certificates: []tls.Certificate{cert},
		RootCAs:      pool,
		MinVersion:   tls.VersionTLS12,
	}
	return &http.Client{
		Timeout:       timeout,
		Transport:     &http.Transport{TLSClientConfig: tlsCfg},
		CheckRedirect: noRedirect,
	}, nil
}

// ParseCAFingerprint normalizes a user-supplied SHA-256 certificate fingerprint
// (as generated by the desktop's provisioning tab or `openssl -fingerprint`):
// whitespace, colons and a `sha256:`/`sha256=` prefix are tolerated, case is
// ignored. Exactly 32 bytes of hex are required — fail-closed on anything else.
func ParseCAFingerprint(s string) ([sha256.Size]byte, error) {
	var fp [sha256.Size]byte
	clean := strings.ToLower(strings.TrimSpace(s))
	clean = strings.TrimPrefix(clean, "sha256:")
	clean = strings.TrimPrefix(clean, "sha256=")
	clean = strings.NewReplacer(":", "", " ", "").Replace(clean)
	raw, err := hex.DecodeString(clean)
	if err != nil || len(raw) != sha256.Size {
		return fp, fmt.Errorf(
			"CA fingerprint must be SHA-256 hex (64 hex chars, colons allowed): %q", s)
	}
	copy(fp[:], raw)
	return fp, nil
}

// NewCAFingerprint builds a client that accepts a server ONLY if the presented
// chain contains a certificate with the given SHA-256 fingerprint AND the leaf
// cryptographically chains to it (anchor verify). The check runs INSIDE the TLS
// handshake, so not a single request byte — in particular the one-time
// provision token — leaves the host before the server proved its identity.
// Hostname is intentionally not enforced: the pin IS the identity (same model
// as the desktop's CaPinVerifier), so reaching the server via IP or an alt
// name keeps working and gateway leaf rotation under the same CA survives.
func NewCAFingerprint(fp [sha256.Size]byte, timeout time.Duration) *http.Client {
	tlsCfg := &tls.Config{
		MinVersion: tls.VersionTLS12,
		// Disables only the DEFAULT verification (system roots + hostname);
		// VerifyPeerCertificate below is the actual, stricter gate.
		InsecureSkipVerify: true,
		VerifyPeerCertificate: func(rawCerts [][]byte, _ [][]*x509.Certificate) error {
			return verifyAnchorFingerprint(rawCerts, fp)
		},
	}
	return &http.Client{
		Timeout:       timeout,
		Transport:     &http.Transport{TLSClientConfig: tlsCfg},
		CheckRedirect: noRedirect,
	}
}

// verifyAnchorFingerprint implements the NewCAFingerprint gate: find the
// fingerprint-matched certificate in the presented chain and verify the leaf
// against it as the ONLY trust anchor. A chain that merely CONTAINS the pinned
// cert but whose leaf does not chain to it (an attacker appending the public CA
// cert to its own leaf) is rejected by the Verify step.
func verifyAnchorFingerprint(rawCerts [][]byte, fp [sha256.Size]byte) error {
	if len(rawCerts) == 0 {
		return fmt.Errorf("server presented no certificates")
	}
	certs := make([]*x509.Certificate, 0, len(rawCerts))
	var anchor *x509.Certificate
	for _, raw := range rawCerts {
		c, err := x509.ParseCertificate(raw)
		if err != nil {
			return fmt.Errorf("presented certificate not parseable: %w", err)
		}
		certs = append(certs, c)
		if anchor == nil && sha256.Sum256(raw) == fp {
			anchor = c
		}
	}
	if anchor == nil {
		return fmt.Errorf(
			"no presented certificate carries the expected CA fingerprint " +
				"(possible MITM — or a wrong/outdated --ca-fp value)")
	}
	leaf := certs[0]
	if leaf.Equal(anchor) {
		return nil // the pinned certificate IS the leaf — direct pin, nothing to chain
	}
	roots := x509.NewCertPool()
	roots.AddCert(anchor)
	intermediates := x509.NewCertPool()
	for _, c := range certs[1:] {
		if !c.Equal(anchor) {
			intermediates.AddCert(c)
		}
	}
	// No DNSName on purpose (see NewCAFingerprint); expiry/EKU stay enforced.
	if _, err := leaf.Verify(x509.VerifyOptions{Roots: roots, Intermediates: intermediates}); err != nil {
		return fmt.Errorf("server leaf does not verify against the pinned CA fingerprint: %w", err)
	}
	return nil
}

// MaxResponseBytes caps how much of a response body is read into memory, so a
// compromised server (or a MITM under persisted INSECURE) cannot OOM the agent with a
// multi-GB response. Legitimate bodies (frpc.toml, JSON, PEM chains) are a few KB to a
// few MB. Exported so hand-rolled reads (provision.callActivate) share the same cap.
const MaxResponseBytes int64 = 10 << 20 // 10 MiB

// Do executes req, reads the full body (capped at MaxResponseBytes), and maps a
// >=300 status to an error (with the body for context). Consolidates the
// request/do/read/status pattern that was hand-rolled across the GET/POST helpers so
// behaviour (size, error text) lives in one place. Callers that need the raw
// *http.Response (e.g. the TLS peer certs for TOFU pinning) keep doing client.Do
// directly.
func Do(client *http.Client, req *http.Request) ([]byte, error) {
	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(io.LimitReader(resp.Body, MaxResponseBytes+1))
	if err != nil {
		return nil, err
	}
	if int64(len(body)) > MaxResponseBytes {
		return nil, fmt.Errorf("Antwort ueberschreitet %d Bytes", MaxResponseBytes)
	}
	if resp.StatusCode >= 300 {
		if isPermanentStatus(resp.StatusCode) {
			return nil, fmt.Errorf("%w: HTTP %d: %s", ErrPermanent, resp.StatusCode, body)
		}
		return nil, fmt.Errorf("HTTP %d: %s", resp.StatusCode, body)
	}
	return body, nil
}
