#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Kevin Stenzel
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# upgrade_path_test.sh — the path every existing installation takes, and the only
# one that was never tested before a release: PREVIOUS RELEASE -> THIS CHECKOUT.
#
# Until now the upgrade was tried exactly once per release, by hand, on Kevin's
# own server. Both services run `alembic upgrade head` at startup, so a migration
# that only works on an empty database, or one that drops data seeded by the older
# schema, is invisible to every test that starts from scratch.
#
#   1  resolve the last PUBLISHED release (anonymous GitHub API, no prereleases)
#   2  bring the stack up from ghcr.io/admincave/adminhelper/*:<tag> and seed it
#      through the admin API (server, FRP config, tunnel)
#   3  swap in the images built from THIS checkout, restart, and assert the seeds
#      are still readable AND a fresh agent report still lands  -> UPGRADE_OK
#   4  run scripts/update.sh --ref <tag> for real against a second, independent
#      install directory: bundle download, minisign verification, atomic swap,
#      healthy `docker compose ps`  -> UPDATE_SH_OK (or UPDATE_SH_SKIP when that
#      release ships no runtime bundle — older tags do not)
#
# Dependency-gated (docker + compose v2, network to api.github.com and ghcr.io,
# go + make for the agent build, minisign for the update signature): exits 75 when
# anything is missing, so it is a SKIP on the dev box and a required step only on
# the hydrated crabbox box — where it belongs in AH_REQUIRED, or a permanently
# skipping step is invisible.
#
# Step 4 brings a SECOND stack up from the UNCHANGED docker-compose.yml, whose
# gateway maps host :443 (plus frps 7000/7443) — those ports must be free on the
# box. Its compose project is per-run and comes down on EXIT with the first one.
#
# Step 4 exercises the RELEASE's update.sh when the checkout's differs (the
# updater re-execs into the one it just unpacked, by design): what it proves is
# that a host on <tag> can move, not that the checkout's swap code is correct.
#
# Run: bash scripts/tests/upgrade_path_test.sh

# ok()/bad() never fail; `cond && ok || bad` assertions are deliberate.
# shellcheck disable=SC2015
set -uo pipefail

# shellcheck source=scripts/tests/lib_e2e_stack.sh
. "$(cd "$(dirname "$0")" && pwd)/lib_e2e_stack.sh"

PASS=0
FAIL=0
ok()  { echo "  ok   $*"; PASS=$((PASS + 1)); }
bad() { echo "  FAIL $*"; FAIL=$((FAIL + 1)); }

GHCR="ghcr.io/admincave/adminhelper"
API="${AH_API_BASE:-https://api.github.com}"

e2e_require go make minisign
# The whole test is about a PUBLISHED release, so no network means no test —
# a SKIP, never a green run that compared the checkout with itself.
curl -fsS --max-time 15 -o /dev/null "$API/repos/AdminCave/AdminHelper" 2>/dev/null \
    || { echo "SKIP: $API not reachable"; exit 75; }

# ── 1. the last published release ────────────────────────────────────────────
# releases/latest excludes drafts and prereleases by definition — exactly the
# "previous release" a user would be coming from.
PREV=$(curl -fsSL --max-time 20 -H "Accept: application/vnd.github+json" \
        "$API/repos/AdminCave/AdminHelper/releases/latest" 2>/dev/null \
       | sed -n 's/.*"tag_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
case "$PREV" in
    v[0-9]*) ;;
    *) echo "SKIP: could not resolve the latest release tag (got '${PREV:-}')"; exit 75 ;;
esac
PREV_VER="${PREV#v}"
ok "previous release: $PREV"

# Every first-party image of that tag must exist, or there is nothing to upgrade
# FROM. A manifest probe costs one round-trip and turns a 20-minute timeout into
# an immediate, honest SKIP.
for img in server gateway ca-issuer monitoring; do
    docker manifest inspect "$GHCR/$img:$PREV_VER" >/dev/null 2>&1 \
        || { echo "SKIP: $GHCR/$img:$PREV_VER not on ghcr"; exit 75; }
done
ok "all four $PREV_VER images are on ghcr"

e2e_init false      # permissive edge: this test is about data + migrations

# Step 4's stack is a second compose project and is NOT covered by e2e_init's
# trap. Chain onto it so a signal takes both down.
UPD_PROJECT="ah-upd-$$"; UPD_DIR=""
upd_teardown() {
    [ -n "$UPD_DIR" ] || return 0
    ( cd "$UPD_DIR" && docker compose -p "$UPD_PROJECT" down -v --remove-orphans >/dev/null 2>&1 ) || true
    UPD_DIR=""
}
upgrade_teardown() { upd_teardown; e2e_teardown; }
trap upgrade_teardown EXIT

# ── the two compose stacks ───────────────────────────────────────────────────
# Phase 1 pins the released images; phase 2 is the repo's own test overlay. Both
# use the SAME project name, so every named volume (postgres-data above all)
# carries over — that carry-over IS the upgrade under test.
PREV_COMPOSE="$E2E_WORK/compose.prev.yml"
cat > "$PREV_COMPOSE" <<YAML
# generated by upgrade_path_test.sh — the released images, on the test ports
services:
  server:
    image: $GHCR/server:$PREV_VER
    volumes:
      - test-data:/app/data
  scheduler:
    image: $GHCR/server:$PREV_VER
  gateway:
    image: $GHCR/gateway:$PREV_VER
    ports: !override
      - "\${ITEST_HTTPS_PORT:-18443}:443"
      - "\${ITEST_ENROLL_PORT:-8444}:8444"
      - "\${ITEST_REPO_PORT:-8445}:8445"
  ca-issuer:
    image: $GHCR/ca-issuer:$PREV_VER
  monitoring:
    image: $GHCR/monitoring:$PREV_VER
volumes:
  test-data:
YAML

dc_prev() { docker compose -p "$E2E_PROJECT" -f "$E2E_REPO_ROOT/docker-compose.yml" \
              -f "$PREV_COMPOSE" --env-file "$E2E_WORK/.env" "$@"; }

wait_gateway() {
    local code
    for _ in $(seq 1 120); do
        code=$(curl -k -s -o /dev/null -w '%{http_code}' --max-time 3 "$E2E_SERVER_URL/" 2>/dev/null || echo 000)
        [ "$code" != "000" ] && return 0
        sleep 2
    done
    return 1
}

# ── 2. the released stack, seeded ────────────────────────────────────────────
echo "[upgrade] starting the $PREV stack..."
if ! dc_prev up -d gateway monitoring >"$E2E_WORK/up-prev.log" 2>&1; then
    tail -30 "$E2E_WORK/up-prev.log"
    bad "the $PREV stack did not start"; exit 1
fi
wait_gateway && ok "$PREV stack live on :$E2E_HTTPS_PORT" \
    || { bad "$PREV gateway never answered"; dc_prev logs --tail 40 gateway; exit 1; }

TOKEN=$(e2e_admin_token)
[ -n "$TOKEN" ] && ok "admin login against $PREV" \
    || { bad "admin login failed on $PREV"; dc_prev logs --tail 40 server; exit 1; }
SERVER_ID=$(e2e_api "$TOKEN" server upgrade-srv upgrade.local) || { bad "seed server"; exit 1; }
CONFIG_ID=$(e2e_api "$TOKEN" config upgrade-frps localhost 7000) || { bad "seed FRP config"; exit 1; }
e2e_api "$TOKEN" tunnel "$SERVER_ID" "$CONFIG_ID" upgrade-tunnel 22 >/dev/null || { bad "seed tunnel"; exit 1; }
# A second populated table across the jump: `connections` is the one every suite
# that starts from scratch leaves empty, so a migration that only works on an
# empty table would pass everywhere else. (No credentials live here — those are
# in the desktop keyring; the model has no secret column.)
CONN_ID=$(e2e_api "$TOKEN" connection upgrade-conn ssh 10.0.0.42 22 root) || { bad "seed connection"; exit 1; }
CONNS_BEFORE=$(e2e_api "$TOKEN" count-connections "$SERVER_ID" 2>/dev/null || echo 0)
BEFORE=$(e2e_api "$TOKEN" count-tunnels "$SERVER_ID" 2>/dev/null || echo 0)
[ "${BEFORE:-0}" -ge 1 ] && ok "seeded on $PREV (server $SERVER_ID, $BEFORE tunnel(s), connection $CONN_ID)" \
    || { bad "seeds not readable on $PREV itself"; exit 1; }

# ── 3. swap in the images from THIS checkout ─────────────────────────────────
# `up --build -d` recreates the containers against the same volumes; both
# services run `alembic upgrade head` on startup, which is the migration under test.
echo "[upgrade] rebuilding from the checkout and restarting..."
e2e_up gateway monitoring && ok "checkout stack live on the $PREV data" \
    || { bad "the checkout stack did not come up over the $PREV data"; e2e_dc logs --tail 40 server; exit 1; }

# The admin password is unchanged, so a successful login already proves the user
# table survived the migration.
TOKEN=$(e2e_admin_token)
[ -n "$TOKEN" ] && ok "admin login after the upgrade" \
    || { bad "admin login broke across the upgrade"; e2e_dc logs --tail 40 server; exit 1; }
AFTER=$(e2e_api "$TOKEN" count-tunnels "$SERVER_ID" 2>/dev/null || echo 0)
# -eq, not -ge: a migration that DUPLICATES rows is as broken as one that loses
# them, and -ge would call it a pass.
[ "${AFTER:-0}" -eq "$BEFORE" ] \
    && ok "tunnels still readable and unchanged after the upgrade ($BEFORE -> $AFTER)" \
    || bad "tunnel count changed across the upgrade ($BEFORE -> ${AFTER:-0})"
CONNS_AFTER=$(e2e_api "$TOKEN" count-connections "$SERVER_ID" 2>/dev/null || echo 0)
[ "${CONNS_AFTER:-0}" -eq "$CONNS_BEFORE" ] \
    && ok "connections still readable and unchanged ($CONNS_BEFORE -> $CONNS_AFTER, incl. $CONN_ID)" \
    || bad "connection count changed across the upgrade ($CONNS_BEFORE -> ${CONNS_AFTER:-0})"

# A migrated database must still ACCEPT writes, not merely answer reads: a real
# agent enrolls against the upgraded stack and pushes one report.
AGENT_BIN="$E2E_REPO_ROOT/apps/agent/bin/adminhelper-agent"
( cd "$E2E_REPO_ROOT/apps/agent" && make build-linux >/dev/null 2>&1 ) && [ -x "$AGENT_BIN" ] \
    && ok "agent built" || bad "agent build failed"
if [ -x "$AGENT_BIN" ]; then
    PTOK=$(e2e_api "$TOKEN" provision-token "$SERVER_ID" 2>/dev/null)
    docker run --rm --network host -v "$AGENT_BIN:/agent:ro" debian:bookworm-slim \
        sh -c "/agent provision --url 'https://localhost:$E2E_HTTPS_PORT' --token '$PTOK' --server-id '$SERVER_ID' --insecure; /agent run --once" \
        > "$E2E_WORK/agent.log" 2>&1
    grep -q "Report gesendet" "$E2E_WORK/agent.log" \
        && ok "a fresh agent report lands on the upgraded stack" \
        || { bad "agent report failed after the upgrade"; tail -20 "$E2E_WORK/agent.log" | sed 's/^/    /'; }
fi

[ "$FAIL" -eq 0 ] && echo "UPGRADE_OK"

# ── 4. scripts/update.sh for real, against a second install ──────────────────
# Its own directory and its own compose project: this is the host-side updater,
# not another copy of the stack above. The release must actually ship a runtime
# bundle — older tags do not, and that is a SKIP, not a failure.
#
# The JSON goes into a variable first: `curl … | grep -q` cannot tell "the asset
# is not there" from "the API did not answer", and the second one would print
# UPDATE_SH_SKIP for something that was never checked.
REL_JSON=""
if ! REL_JSON=$(curl -fsSL --max-time 20 -H "Accept: application/vnd.github+json" \
        "$API/repos/AdminCave/AdminHelper/releases/tags/$PREV" 2>/dev/null); then
    bad "could not ask GitHub for the assets of $PREV — update.sh path not verified"
elif printf '%s' "$REL_JSON" | grep -q "\"name\": *\"adminhelper-runtime-$PREV\.tar\.gz\""; then
    INST="$E2E_WORK/install"; mkdir -p "$INST/scripts"
    cp "$E2E_REPO_ROOT/docker-compose.yml" "$INST/"
    # .env.example is NOT optional: update.sh snapshots (docker-compose.yml,
    # .env.example, scripts) before the swap, and GNU tar exits 2 on a missing
    # member — the updater would die before it changed anything. It is also what
    # drives the additive .env migration, i.e. the "new keys arrive" property.
    cp "$E2E_REPO_ROOT/.env.example" "$INST/"
    cp "$E2E_REPO_ROOT/scripts/update.sh" "$INST/scripts/"
    # A host in the PREVIOUS state: the image pins are what update.sh reads as
    # "installed", and the ports must not collide with the stack still running above.
    {
        sed -n 's/^\(DOMAIN\|SECRET_KEY\|POSTGRES_PASSWORD\|CA_ROOT_PASSPHRASE\|MONITOR_API_KEY\|ADMIN_PASSWORD\)=.*/&/p' "$E2E_WORK/.env"
        echo "MTLS_ENFORCE=false"
        echo "ENROLL_PORT=$(( E2E_HTTPS_PORT + 1 ))"
        echo "REPO_PORT=$(( E2E_HTTPS_PORT + 2 ))"
        # An OLDER pin than the target, so `--ref` actually MOVES the pins and the
        # assertion below observes something. Pinning $PREV_VER here would make it
        # a tautology: update.sh would write the string the test just wrote.
        # 0.0.1 never exists on ghcr and is never pulled — update.sh re-pins
        # before it pulls, and --ref skips the downgrade and same-version guards.
        for s in SERVER GATEWAY CA_ISSUER MONITORING; do
            case "$s" in SERVER) i=server ;; GATEWAY) i=gateway ;; CA_ISSUER) i=ca-issuer ;; *) i=monitoring ;; esac
            echo "${s}_IMAGE=$GHCR/$i:0.0.1"
        done
        # Per-run project: compose reads ./.env itself, the key is not in
        # .env.example so the additive migration leaves it alone, and two lanes on
        # one box would otherwise share containers.
        echo "COMPOSE_PROJECT_NAME=$UPD_PROJECT"
    } > "$INST/.env"
    # e2e_init's EXIT trap only knows the first stack. Without this, a SIGINT in
    # the middle of step 4 leaves containers and volumes behind while
    # `rm -rf "$E2E_WORK"` pulls their compose files out from under them.
    UPD_DIR="$INST"
    F4="$FAIL"                     # so the marker below reflects STEP 4, not step 3
    echo "[upgrade] scripts/update.sh --ref $PREV in $INST ..."
    ( cd "$INST" && bash scripts/update.sh --ref "$PREV" --skip-backup --no-rollback --yes ) \
        > "$E2E_WORK/update.log" 2>&1
    urc=$?
    tail -25 "$E2E_WORK/update.log" | sed 's/^/    /'
    if [ "$urc" -ne 0 ]; then
        bad "update.sh --ref $PREV exited $urc"
    else
        # Signature: the whole point of the bundle path. Without this assertion an
        # unarmed MINISIGN_PUBKEY would fall back to checksums and still be green.
        grep -q "Release-Signatur verifiziert (minisign)" "$E2E_WORK/update.log" \
            && ok "update.sh: the bundle's SHA256SUMS verified against the pinned key" \
            || bad "update.sh: no minisign verification in the log — checksum-only path?"
        # The version truth of an install is the image pin in .env; an install
        # directory has no VERSION marker by design (it is not in MANIFEST.sha256,
        # and install.sh removes it).
        grep -qx "SERVER_IMAGE=$GHCR/server:$PREV_VER" "$INST/.env" \
            && ok "update.sh: the image pins moved to $PREV_VER" \
            || bad "update.sh: SERVER_IMAGE not pinned to $PREV_VER after the update"
        [ -x "$INST/scripts/install.sh" ] && [ -x "$INST/scripts/restore.sh" ] \
            && ok "update.sh: the runtime scripts were swapped in" \
            || bad "update.sh: runtime scripts missing after the swap"
        # --all is load-bearing: without it `ps` lists ONLY running containers, so
        # "nothing is in a non-running state" would be trivially true for a stack
        # that is entirely dead. Name the services that must be up as well.
        states="$( cd "$INST" && docker compose -p "$UPD_PROJECT" ps --all --format '{{.Service}} {{.State}}' 2>/dev/null )"
        notrunning="$(printf '%s\n' "$states" | grep -v '^$' | grep -v ' running$' | paste -sd' ' -)"
        missing=""
        for svc in postgres server gateway ca-issuer monitoring; do
            printf '%s\n' "$states" | grep -q "^$svc running$" || missing="$missing $svc"
        done
        [ -z "$missing" ] && [ -z "$notrunning" ] \
            && ok "update.sh: the whole updated stack is up ($(printf '%s\n' "$states" | grep -c .) containers)" \
            || bad "update.sh: after the update — missing:${missing:- none} not running: ${notrunning:- none}"
    fi
    upd_teardown
    [ "$FAIL" -eq "$F4" ] && echo "UPDATE_SH_OK"
else
    # A plain echo, not ok(): "did not run" must never add to the passed count.
    echo "UPDATE_SH_SKIP"
    echo "  --   release $PREV ships no runtime bundle — update.sh path not applicable"
fi

echo ""
echo "upgrade_path_test: $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ]
