#!/usr/bin/env bash
# SPDX-FileCopyrightText: Kevin Stenzel
# SPDX-License-Identifier: GPL-3.0-or-later
#
# lane.sh — manage parallel build lanes (git worktree + VM wiring).
# A lane = its own worktree + feature branch + warm VM, tagged with the lane name
# so no lane can sweep another's boxes (see vm_lane in scripts/vm/lib.sh).
# Full workflow: AUTONOMOUS.md ("Parallel-Betrieb").
#
#   bash scripts/dev/lane.sh new <slug>   worktree ../AdminHelper-<slug> on
#                                         feature/<slug> (forked from main); writes
#                                         .vm/lane, copies .claude/settings.local.json,
#                                         writes the lane's own .devenv.sh and creates
#                                         its test database, links the frpc sidecar and
#                                         the component venvs; refuses without the plan
#                                         committed on feature/<slug> (else on main)
#   bash scripts/dev/lane.sh done <slug>  destroy the lane's VMs, then remove
#                                         worktree + branch (branch only if merged),
#                                         the lane's test database and its venv;
#                                         refuses while a process works in the lane
#   bash scripts/dev/lane.sh list         worktrees + their warm boxes
set -euo pipefail

CMD="${1:-}"
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"
# shellcheck source=scripts/vm/lib.sh
. "$ROOT/scripts/vm/lib.sh"
# Refuse to run from a linked worktree (its .git is a FILE): `done` would remove
# the very worktree the session sits in, leaving the caller in a deleted cwd.
[ -d "$ROOT/.git" ] || { echo "lane.sh must run from the MAIN checkout, not a worktree"; exit 1; }

# The lane's database and venv, derived from the slug alone so `new` and `done`
# cannot disagree about what belongs to the lane. check_slug has limited the slug
# to [a-z0-9-] before either is called.
lane_db_name() { printf 'adminhelper_test_%s' "${1//-/_}"; }
lane_venv() { printf '%s/.cache/ah-venv-%s' "$HOME" "$1"; }

# The lane's .devenv.sh: the main checkout's file first, then the two values a
# second checkout must not share with it. One test database for two server
# suites means one run's drop_all takes the other's tables (2026-09-18); one venv
# means two runs installing into it at once. `${AH_TEST_DB%/*}` keeps everything
# up to the database name — a query string (?sslmode=…) after it would be lost;
# the URL in the main checkout's file has none.
lane_devenv() {
  local slug="$1"
  cat <<EOF
# Generated by scripts/dev/lane.sh new $slug — this lane's own environment.
# lane.sh done removes it with the lane; edit the main checkout's file instead.
. "$ROOT/.devenv.sh"
[ -z "\${AH_TEST_DB:-}" ] || export AH_TEST_DB="\${AH_TEST_DB%/*}/$(lane_db_name "$slug")"
export AH_VENV="\$HOME/.cache/ah-venv-$slug"
EOF
}

# createdb/dropdb on the server the main checkout's AH_TEST_DB names, with its
# credentials. That URL is SQLAlchemy's (postgresql+psycopg://…); libpq wants
# plain postgresql://, and --maintenance-db takes a whole connection string.
# The file is sourced with -e/-u off: it is written for an interactive shell,
# and nvm.sh in it does not survive `set -u`.
lane_db() {  # lane_db create|drop <slug>
  local url
  url="$(set +eu; . "$ROOT/.devenv.sh" >/dev/null 2>&1; printf '%s' "${AH_TEST_DB:-}")"  # review: ok sources an interactive-shell file, silences no test
  if [ -z "$url" ]; then
    echo "  no AH_TEST_DB in .devenv.sh — no database of the lane's own"
    return 0
  fi
  url="$(printf '%s' "$url" | sed -E 's#^postgresql\+[a-z0-9]+://#postgresql://#')"
  # The password travels in the environment, not on the command line: every local
  # user can read a process's arguments (/proc/<pid>/cmdline), only its owner its
  # environment. The URL percent-encodes the password; PGPASSWORD takes it raw.
  local pass="" envp=()
  if [[ "$url" =~ ^(postgresql://[^:@/]+):([^@]*)@(.*)$ ]]; then
    pass="${BASH_REMATCH[2]}"
    url="${BASH_REMATCH[1]}@${BASH_REMATCH[3]}"
    pass="${pass//\\/\\\\}"
    pass="$(printf '%b' "${pass//%/\\x}")"
  fi
  [ -n "$pass" ] && envp=(PGPASSWORD="$pass")
  case "$1" in
    create) env "${envp[@]}" createdb --maintenance-db="$url" "$(lane_db_name "$2")" ;;
    drop)   env "${envp[@]}" dropdb --if-exists --maintenance-db="$url" "$(lane_db_name "$2")" ;;
  esac
}

# The lane's ownership mark, in the MAIN checkout's .vm (gitignored), so it
# outlives a worktree somebody removed by hand. `done` takes a slug's database
# and venv only when the mark says `new` made them: the names are guessable,
# and without it `done fable` dropped a hand-made adminhelper_test_fable and
# ~/.cache/ah-venv-fable (review, 2026-09-23).
lane_mark() { printf '%s/.vm/lanes/%s' "$ROOT" "$1"; }

# lane_link_dir <worktree> <dir> — link every entry of the main checkout's <dir>
# into a REAL <dir> in the lane. .gitignore matches these as directories
# (`.venv/`, `binaries/`); a symlink in their place is no directory to it, so it
# would be an untracked file — noise in every git status of the lane, one
# `git add -A` away from a commit, and a worktree `done` calls unclean. A venv
# still works through the links: python finds pyvenv.cfg next to bin/.
# "For reading" is how the lane uses them, not a lock: they are ordinary links,
# and a `pip install` through apps/<c>/.venv would change the main checkout's
# venv. run.sh installs into AH_VENV, which is the lane's own.
lane_link_dir() {
  local wt="$1" dir="$2" entry
  [ -d "$ROOT/$dir" ] || return 0
  mkdir -p "$wt/$dir"
  for entry in "$ROOT/$dir"/* "$ROOT/$dir"/.[!.]* "$ROOT/$dir"/..?*; do
    [ -e "$entry" ] || [ -L "$entry" ] || continue
    ln -sfn "$entry" "$wt/$dir/${entry##*/}"
  done
}

lane_new() {
  local slug="${1:?usage: lane.sh new <slug>}"
  # The slug IS the lane id, written to .vm/lane below (vm_lane normalizes
  # lossily: foo_bar and foo.bar would both become lane foo-bar and SHARE their
  # VMs) — so only allow the charset that survives normalization unchanged.
  local wt="../AdminHelper-$slug" branch="feature/$slug"
  [ -e "$wt" ] && { echo "lane dir $wt already exists"; exit 1; }
  # The plan lies where the build will see it (R-0065): the gate commits spec and
  # ledger as the first commit of feature/<slug>, so on that branch when it
  # exists, else on main. A worktree only sees COMMITTED state, and a lane
  # without its plan cannot build — so this refuses before a worktree exists.
  local where=main
  git show-ref --verify --quiet "refs/heads/$branch" && where="$branch"
  if ! git cat-file -e "$where:tasks/$slug.md" 2>/dev/null; then
    echo "tasks/$slug.md is not committed on $where — a lane only sees committed state."
    echo "  Commit the plan there first (chore(plan): add spec + ledger for $slug)."
    exit 1
  fi
  # A mark without a worktree is a lane nobody closed; a venv of this name
  # without a mark is somebody's handwork. Adopting either would make `done`
  # take it later.
  if [ -e "$(lane_mark "$slug")" ]; then
    echo "lane $slug was never closed ($(lane_mark "$slug")) — run: bash scripts/dev/lane.sh done $slug"
    exit 1
  fi
  if [ -e "$(lane_venv "$slug")" ]; then
    echo "$(lane_venv "$slug") exists and belongs to no lane — pick another slug, or remove it yourself"
    exit 1
  fi
  # The database first, then the mark, then the worktree: a createdb that fails
  # (the name is taken) must leave nothing behind, and every step after it takes
  # back what came before. The mark's directory is made before anything else.
  mkdir -p "$ROOT/.vm/lanes"
  if [ -f .devenv.sh ]; then
    lane_db create "$slug" || {
      echo "  createdb $(lane_db_name "$slug") failed — nothing of lane $slug was created."
      echo "  If that database exists and belongs to no lane, pick another slug."
      exit 1
    }
  fi
  if ! printf 'lane %s, created %s\n' "$slug" "$(date -Is)" > "$(lane_mark "$slug")"; then
    echo "  could not write the mark $(lane_mark "$slug") — taking the database back"
    [ ! -f .devenv.sh ] || lane_db drop "$slug" \
      || echo "  dropdb failed too — $(lane_db_name "$slug") is left behind, drop it by hand"
    exit 1
  fi
  local added=1
  if git show-ref --verify --quiet "refs/heads/$branch"; then
    git worktree add "$wt" "$branch" || added=0
  else
    git worktree add -b "$branch" "$wt" main || added=0
  fi
  if [ "$added" = 0 ]; then
    echo "  git worktree add failed — taking back the database and the mark"
    if [ -f .devenv.sh ] && ! lane_db drop "$slug"; then
      # The mark stays: it is what lets a later `done` drop this database.
      echo "  dropdb failed too — run: bash scripts/dev/lane.sh done $slug"
      exit 1
    fi
    rm -f "$(lane_mark "$slug")"
    exit 1
  fi
  # The lane identity, explicitly: vm.py and lib.sh both read .vm/lane, so every
  # VM this worktree clones carries `lane-<slug>` and no other lane's reap can
  # take it. Deriving the id from the directory name is gone — a file cannot be
  # guessed wrong by one side and right by the other.
  mkdir -p "$wt/.vm" && printf '%s\n' "$slug" > "$wt/.vm/lane"
  # Per-machine files the lane needs (both gitignored). settings.local.json is
  # WRITTEN by Claude Code (permission grants): a symlink would make N lane
  # sessions read-modify-write ONE shared file → COPY. .devenv.sh is the lane's
  # own (lane_devenv above), and so is the database it points at.
  [ -f .claude/settings.local.json ] \
    && cp .claude/settings.local.json "$wt/.claude/settings.local.json"
  [ ! -f .devenv.sh ] || lane_devenv "$slug" > "$wt/.devenv.sh"
  # Gitignored parts of the main checkout that a build needs, linked for
  # reading: the frpc sidecar cargo test wants, and the component venvs that
  # carry the ruff CI pins (without them run.sh finds no ruff at all).
  lane_link_dir "$wt" apps/desktop/src-tauri/binaries
  local c
  for c in server monitoring ca-issuer; do lane_link_dir "$wt" "apps/$c/.venv"; done
  echo ""
  echo "── lane $slug ready ──"
  echo "  start:  cd $wt && claude --model opus --permission-mode acceptEdits"
  echo "  then:   /feature-build tasks/$slug.md"
  echo "  (ledger head: 'Fast-Suite: vm' keeps the dev box free; local runs work too —"
  echo "   own test DB, linked venvs, and the shared python lock queues the heavy steps)"
}

# lane_busy <worktree> — "pid command" for every process of this user whose
# working directory lies in the lane. A session left in a lane that `done`
# removes sits in a deleted cwd and cannot work any more (2026-09-22). Linux
# only: without /proc this finds nothing and would let `done` go ahead.
lane_busy() {
  local wt me proc pid cwd
  wt="$(cd "$1" && pwd -P)" || return 0
  me="$(id -u)"
  for proc in /proc/[0-9]*; do
    pid="${proc#/proc/}"
    [ "$(stat -c %u "$proc" 2>/dev/null)" = "$me" ] || continue
    cwd="$(readlink "$proc/cwd" 2>/dev/null)" || continue
    case "$cwd" in
      "$wt"|"$wt"/*) printf '%s %s\n' "$pid" "$(tr '\0' ' ' < "$proc/cmdline" 2>/dev/null | cut -c1-120)" ;;
    esac
  done
}

lane_done() {
  local slug="${1:?usage: lane.sh done <slug>}"
  local wt="../AdminHelper-$slug" branch="feature/$slug"
  # Before anything of the lane is touched, VMs included. No force switch: that
  # would be exactly the move that stranded a session on 2026-09-22.
  if [ -d "$wt" ]; then
    local busy
    busy="$(lane_busy "$wt")"
    if [ -n "$busy" ]; then
      echo "lane $slug is still in use — these processes work in $wt:"
      printf '%s\n' "$busy" | sed 's/^/  /'
      echo "End the session(s) in the lane, then run again: bash scripts/dev/lane.sh done $slug"
      exit 1
    fi
  fi
  # Reap with the MAIN checkout's (current) scripts, but against the LANE's own
  # state: the lane's copies fork from main and may predate a change here, while
  # the VMIDs that have to go are recorded in the lane's .vm/warm.env. Abort
  # instead of hiding a reap failure — once the worktree is gone, a leaked VM has
  # no record left to find it by.
  # The state dir is the LANE's when the worktree is still there, and a path that
  # cannot exist when it is not: the warm.env step is then a no-op, but `vm.py
  # reap` and the closing `vm.py list` still run against `lane-$slug`. A worktree
  # somebody removed by hand is exactly the case that leaks, so it must not be
  # the case that silently skips the sweep. Never the MAIN checkout's .vm — that
  # would destroy this session's own warm box.
  local state
  if [ -d "$wt" ]; then
    state="$(cd "$wt" && pwd)/.vm"
  else
    # No worktree, no warm.env — so `reap.sh` would find no VMIDs to destroy and
    # `vm.py reap` only takes what has already expired. A LIVE box of this lane
    # would then burn until its ttl while the closing listing correctly calls it
    # a leak and aborts the removal. Destroy the lane outright: the lane is
    # being dismantled, and nothing else may carry its tag.
    state="$ROOT/.vm/absent-$slug"
    vm_py destroy --lane "$slug" 2>&1 | sed 's/^/  /' \
      || { echo "  destroy failed — VMs of lane $slug may still run"; exit 1; }
    # A hand-deleted directory leaves the worktree REGISTERED and prunable, and
    # git then refuses `branch -d` — even for a fully merged branch — with "is
    # used by worktree". Without this the run would end on the wrong reason
    # ("not merged"), and `-D` would fail the same way.
    git -C "$ROOT" worktree prune >/dev/null 2>&1 || true
  fi
  AH_VM_STATE_DIR="$state" bash "$ROOT/scripts/vm/reap.sh" --lane "$slug" \
    || { echo "  reap failed — NOT removing the worktree (VMs may still run)"; exit 1; }
  # `reap.sh` ends with a listing that exits non-zero on a leak, so reaching here
  # means this lane is clear. The main checkout's own boxes are never touched:
  # every verb above is scoped to `lane-$slug`.
  if [ -d "$wt" ]; then
    git worktree remove "$wt" \
      || { echo "worktree not clean — inspect it, then: git worktree remove --force $wt"; exit 1; }
  fi
  # The lane's database and venv go with it, only after the worktree (when that
  # refused to go, nothing of the lane has been taken yet), and only when the
  # mark says they are the lane's.
  if [ ! -e "$(lane_mark "$slug")" ]; then
    echo "  no ownership mark for lane $slug — database $(lane_db_name "$slug") and"
    echo "  $(lane_venv "$slug") are not this lane's, if they exist at all; left alone"
  elif [ -f "$ROOT/.devenv.sh" ]; then
    lane_db drop "$slug" \
      || { echo "  dropdb failed — database $(lane_db_name "$slug") is left behind"; exit 1; }
    rm -rf "$(lane_venv "$slug")"
    rm -f "$(lane_mark "$slug")"
  else
    # Without the file there is no telling which server holds the database, and a
    # database left behind silently is the leak this command exists to prevent.
    # The mark stays, so a later `done` still knows the database is the lane's.
    echo "  WARN: no .devenv.sh in the main checkout — database $(lane_db_name "$slug") is NOT dropped;"
    echo "        drop it by hand on the server AH_TEST_DB named (dropdb $(lane_db_name "$slug"))"
    rm -rf "$(lane_venv "$slug")"
  fi
  if git show-ref --verify --quiet "refs/heads/$branch"; then
    git branch -d "$branch" 2>/dev/null && echo "  branch $branch deleted (was merged)" \
      || echo "  branch $branch kept (not merged — git branch -D $branch if you mean it)"
  fi
}

lane_list() {
  git worktree list
  local wt
  # sed, not awk '{print $2}': worktree paths may contain spaces.
  while read -r wt; do
    [ "$wt" = "$ROOT" ] && continue
    [ -f "$wt/.vm/warm.env" ] || continue
    echo "  $wt boxes: $(grep -E '^(desktop|server)=' "$wt/.vm/warm.env" | tr '\n' ' ')"
  done < <(git worktree list --porcelain | sed -n 's/^worktree //p')
}

# Both verbs, one guard: `done` reaps by lane, so a slug it accepts but `new`
# would have rejected sweeps the wrong lane. `main` and the dash-edge forms are
# the dangerous ones — vm_lane strips leading and trailing dashes, so `-foo`
# becomes lane `foo` and `-` becomes lane `main`, the shared checkout's own lane.
check_slug() {
  case "${1:-}" in
    "") echo "usage: lane.sh <new|done> <slug>"; exit 2 ;;
    main|-*|*-) echo "slug must not be 'main' and must not start or end with '-'"; exit 2 ;;
    *[!a-z0-9-]*) echo "slug must be lowercase [a-z0-9-] only (the slug is the lane id)"; exit 2 ;;
  esac
  # adminhelper_test_ + 40 stays under the 63 bytes Postgres keeps of a name.
  [ "${#1}" -le 40 ] || { echo "slug must be at most 40 characters"; exit 2; }
}

case "$CMD" in
  new)  check_slug "${2:-}"; lane_new "${2:-}" ;;
  done) check_slug "${2:-}"; lane_done "${2:-}" ;;
  list) lane_list ;;
  *) echo "usage: lane.sh <new|done> <slug> | lane.sh list"; exit 2 ;;
esac
