# SPDX-FileCopyrightText: 2026 Kevin Stenzel
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""Tests for scripts/dev/lock-pins.py.

The lock and the installed state are fixtures in tmp_path (``--freeze``), except
for the two cases that read the running environment through importlib.metadata.
Every case asserts more than the exit code, so a script that always says 0 —
or always says 1 — fails here.
"""

from __future__ import annotations

import pathlib
import subprocess
import sys

import pytest

SCRIPT = pathlib.Path(__file__).resolve().parents[1] / "lock-pins.py"

# The shape pip-compile --generate-hashes writes: pin, hash continuations, "via" comments.
LOCK = """\
#
# This file is autogenerated by pip-compile with Python 3.12
#
alembic==1.18.4 \\
    --hash=sha256:aaaa \\
    --hash=sha256:bbbb
    # via -r requirements.in
Typing_Extensions==4.15.0 \\
    --hash=sha256:cccc
    # via
    #   alembic
uvicorn[standard]==0.49.0 \\
    --hash=sha256:dddd
    # via -r requirements.in
"""

FREEZE = """\
alembic==1.18.4
pytest==9.1.1
typing_extensions==4.15.0
uvicorn==0.49.0
-e git+https://example.invalid/x.git@abc#egg=x
"""


def run(
    tmp_path: pathlib.Path, lock: str, freeze: str | None = FREEZE
) -> subprocess.CompletedProcess[str]:
    lock_file = tmp_path / "requirements.txt"
    lock_file.write_text(lock, encoding="utf-8")
    argv = [sys.executable, str(SCRIPT), str(lock_file)]
    if freeze is not None:
        freeze_file = tmp_path / "freeze.txt"
        freeze_file.write_text(freeze, encoding="utf-8")
        argv += ["--freeze", str(freeze_file)]
    return subprocess.run(argv, capture_output=True, text=True, timeout=30)


def test_every_pin_installed_as_locked(tmp_path):
    r = run(tmp_path, LOCK)
    assert r.returncode == 0, r.stdout + r.stderr
    # Three pins, not four: the hash and via lines are not pins, the extra is not a package.
    assert "3 pins installed as locked" in r.stdout


def test_a_drifted_pin_is_named_with_both_versions(tmp_path):
    r = run(tmp_path, LOCK, FREEZE.replace("alembic==1.18.4", "alembic==1.19.0"))
    assert r.returncode == 1, r.stdout + r.stderr
    assert "drift    alembic: locked 1.18.4, installed 1.19.0" in r.stdout
    assert "1 of 3 pins differ" in r.stdout
    assert "uvicorn" not in r.stdout


def test_a_missing_pin_is_named(tmp_path):
    r = run(tmp_path, LOCK, FREEZE.replace("typing_extensions==4.15.0\n", ""))
    assert r.returncode == 1, r.stdout + r.stderr
    assert "missing  typing-extensions: locked 4.15.0, not installed" in r.stdout
    assert "1 of 3 pins differ" in r.stdout


def test_extras_are_compared_without_the_extra(tmp_path):
    r = run(tmp_path, LOCK, FREEZE.replace("uvicorn==0.49.0", "uvicorn==0.50.0"))
    assert r.returncode == 1, r.stdout + r.stderr
    assert "drift    uvicorn: locked 0.49.0, installed 0.50.0" in r.stdout


def test_every_problem_is_listed_not_just_the_first(tmp_path):
    freeze = FREEZE.replace("alembic==1.18.4", "alembic==1.0").replace("uvicorn==0.49.0\n", "")
    r = run(tmp_path, LOCK, freeze)
    assert r.returncode == 1, r.stdout + r.stderr
    assert "drift    alembic" in r.stdout
    assert "missing  uvicorn" in r.stdout
    assert "2 of 3 pins differ" in r.stdout


@pytest.mark.parametrize(
    "lock",
    [
        pytest.param("", id="empty"),
        pytest.param("#\n# only comments\n#\n", id="comments-only"),
    ],
)
def test_a_lock_without_pins_is_never_green(tmp_path, lock):
    r = run(tmp_path, lock)
    assert r.returncode == 2, r.stdout + r.stderr
    assert "no pins" in r.stderr


def test_an_unreadable_lock_is_exit_2(tmp_path):
    r = subprocess.run(
        [sys.executable, str(SCRIPT), str(tmp_path / "nope.txt")],
        capture_output=True,
        text=True,
        timeout=30,
    )
    assert r.returncode == 2, r.stdout + r.stderr
    assert "nope.txt" in r.stderr


@pytest.mark.parametrize(
    "line",
    [
        pytest.param('colorama==0.4.6 ; sys_platform == "win32"', id="marker"),
        pytest.param("alembic>=1.18", id="range"),
        pytest.param("-e ./vendored", id="editable"),
        pytest.param("--index-url https://example.invalid/simple", id="option"),
    ],
)
def test_a_line_it_cannot_read_is_refused_not_skipped(tmp_path, line):
    r = run(tmp_path, LOCK + line + "\n")
    assert r.returncode == 2, r.stdout + r.stderr
    assert f"line {LOCK.count(chr(10)) + 1} is not a pin" in r.stderr and line in r.stderr


def test_the_running_environment_is_read_by_default(tmp_path):
    installed = pytest.__version__
    r = run(tmp_path, f"pytest=={installed}\n", freeze=None)
    assert r.returncode == 0, r.stdout + r.stderr
    assert "1 pins installed as locked" in r.stdout

    r = run(tmp_path, "pytest==0.0.1\n", freeze=None)
    assert r.returncode == 1, r.stdout + r.stderr
    assert f"drift    pytest: locked 0.0.1, installed {installed}" in r.stdout
